[package]
name = "fdc-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
fdc-core = { path = "../fdc-core" }
fdc-storage = { path = "../fdc-storage" }
fdc-orchestrator = { path = "../fdc-orchestrator" }
fdc-barter = { path = "../fdc-adapter/barter" }
futures = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
rust_decimal = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
