[package]
name = "fdc-barter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
fdc-core = { path = "../../fdc-core" }
barter-data = { git = "https://github.com/mountainsea-lab/barter-rs.git", rev = "91a4d7aa45c03cbaee51c4f9451bf78c38e9f8a1" }
barter-instrument = { git = "https://github.com/mountainsea-lab/barter-rs.git", rev = "91a4d7aa45c03cbaee51c4f9451bf78c38e9f8a1" }
barter-integration = { git = "https://github.com/mountainsea-lab/barter-rs.git", rev = "91a4d7aa45c03cbaee51c4f9451bf78c38e9f8a1", features = ["error", "metric", "protocol", "serde"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
